project:
  type: website
  output-dir: docs

website:
  title: "Yuki Matsuura"
  google-analytics: "G-8Z5QMTEYRY"
  page-footer: "© 2026 Yuki Matsuura" 
  reader-mode: true
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: work.qmd
        text: Work
      - href: cv.qmd
        text: CV

format:
  html:
    theme: journal
    toc: true



